spring:
  application:
    name: davide-service
  config:
    import: "optional:configserver:"
    cloud:
      config:
        uri: http://catalog-config-server:8888
        fail-fast: true
        retry:
          max-attempts: 10
          max-interval: 3000
          multiplier: 1.1
          initial-interval: 1000
  liquibase:
    url: jdbc:postgresql://polar-postgres:5432/polardb_catalog
    user: user
    password: password
    change-log: classpath:/db/changelog/db.changelog-master.sql
  r2dbc:
    url: r2dbc:postgresql://polar-postgres:5432/polardb_catalog
    username: user
    password: password


server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info

polar:
  message: Whatever from application.yaml
