version: '3.1'

services:
  catalog-config-server:
    image: ghcr.io/avrabie/catalog-config-server:latest
    restart: always
    ports:
      - "8888:8888"
    networks:
      - catalog-network
    container_name: catalog-config-server

  polar-postgres:
    image: postgres
    restart: always
    container_name: polar-postgres
#    depends_on:
#      - catalog-config-server
    networks:
      - catalog-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: polardb_catalog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password




  catalog-service:
    image: ghcr.io/avrabie/catalog-service:latest
    restart: always
    depends_on:
      - polar-postgres
#      - catalog-config-server
    ports:
      - "8080:9001"
      - "8001:8001"
    networks:
        - catalog-network
    container_name: catalog-service
    environment:
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_CONFIG_CLOUD_CONFIG_URI=http://catalog-config-server:8888


networks:
  catalog-network:
    driver: bridge