version: '3.1'

services:
  polar-postgres:
    image: postgres
    restart: always
    container_name: polar-postgres
    networks:
      - catalog-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: polardb_catalog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  catalog-config-server:
    image: ghcr.io/avrabie/catalog-config-server:latest
    restart: always

    ports:
      - "8888:8888"
    networks:
        - catalog-network
    container_name: config-server


  catalog-service:
    image: ghcr.io/avrabie/catalog-service:latest
    restart: always
    depends_on:
      - polar-postgres
      - catalog-config-server
    ports:
      - "8080:9001"
      - "8001:8001"
    networks:
        - catalog-network
    container_name: catalog-service
    environment:
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001


networks:
  catalog-network:
    driver: bridge