-- liquibase formatted sql

-- changeset moldo:1698504628971-1
CREATE TABLE "customer" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "first_name" VARCHAR(255), "last_name" VARCHAR(255), CONSTRAINT "customer_pkey" PRIMARY KEY ("id"));
-- rollback drop table customer;

-- changeset moldo:1698504628971-2
CREATE TABLE "book" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 3) NOT NULL, "author" VARCHAR(255) NOT NULL, "isbn" VARCHAR(255) NOT NULL, "price" FLOAT8 NOT NULL, "title" VARCHAR(255) NOT NULL, "version" INTEGER NOT NULL, CONSTRAINT "book_pkey" PRIMARY KEY ("id"));

-- changeset moldo:1698504628971-3
ALTER TABLE "book" ADD CONSTRAINT "book_isbn_key" UNIQUE ("isbn");

-- changeset moldo:1698504628971-4
ALTER TABLE "book" ADD  created_date timestamp;
ALTER TABLE "book" ADD  last_modified_date   timestamp;


